apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic5-wj0u
  namespace: mreid1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ff6402c459117368b99f368471655dbfae1049cb3afcb406554fd891503e99bd
        name: my-python
        resources: {}
status: {}
